apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: ensurevalidatedrepos
spec:
  crd:
    spec:
      names:
        kind: EnsureValidatedRepos
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            repo:
              type: string

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
{{file.Read "./gatekeeper/validated-repo.rego" | indent 8 }}

--- 

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EnsureValidatedRepos
metadata:
  name: ensurevalidatedrepos
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    repo: "k3d-registry"
