apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: ensurevalidatedrepos
spec:
  crd:
    spec:
      names:
        kind: EnsureValidatedRepos
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            repo:
              type: string

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
{{file.Read "./validated-repo/validated-repo.rego" | indent 8 }}


