name: Run Opa Tests
on: [push]
jobs:
  Run-Opa-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: artis3n/setup-conftest@v0
      - id: verify
        run: conftest verify -p ensure-only-validated-repo