name: Run Opa Tests
on: [push]
jobs:
  Run-Opa-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test
      uses: instrumenta/conftest-action@master
      with:
        policy: ./ensure-only-validated-repo
        files: ./ensure-only-validated-repo/*-test.rego